---
title: "Merged Dataset"
author: "Yuru Chen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
```


```{r}
load("~/Desktop/Empirical Asset Pricing/project/GBR_DS_monthly.RData")
load("~/Desktop/Empirical Asset Pricing/project/GBR_DS_static.RData")
load("~/Desktop/Empirical Asset Pricing/project/GBR_WS_yearly.RData")

DS_monthly <- as.data.table(DS.monthly)
DS_static <- as.data.table(DS.static)
WS_yearly <- as.data.table(WS.yearly)
```

```{r}
DS_monthly[,month:=month(Date)]
DS_monthly[,year:=year(Date)]
DS_monthly[,hcdec:=ifelse(month >= 7, year-1, year-2)]

DS_monthly[, c("country","Date"):=NULL]
DS_monthly <- DS_monthly[,c(1,19,18,2,20,3:17)]
```


```{r}
WS_yearly[,c("country","Stock"):=NULL]
WS_yearly <- WS_yearly[,c(1,5,2,4,3,6:109)]
```


```{r}
panel_country <- merge(x=DS_monthly, y=WS_yearly, by.x = c("Id","hcdec"), by.y = c("Id","Year"), all= 1)

```



```{r}
save(panel_country,file="panel_country_June30.RData")
```


```{r}
DTB6_monthly[month %in% 1:9, month_new:=paste("0",month,sep = "")] 
DTB6_monthly[month %in% 10:12, month_new:=month] 
DTB6_monthly$ym <- paste(DTB6_monthly$year,DTB6_monthly$month_new,sep = ".")
DTB6_monthly[,month_new:=NULL]
```

```{r}
save(DTB6_monthly,file="DTB6_monthly_July01.RData")
```

