---
title: "Tangent_Portfolio_Calculation"
author: "Yasu"
date: "2023-07-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Data
### 6 factor
```{r}
load("/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/stock_20_6_mean36.RData")

load("/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/stock_20_6_cum.RData")
```

```{r}
load("Univariate_Sort_Set.RData")
```
## Stock List : monthly_6 (factor)_mean36_20 (stocks)
```{r}
quarterly_6_mean_20 <- stock_20_6_mean36 %>% 
  select(Id, ym)

monthly_6_mean_20 <-quarterly_6_mean_20
```

## Stock List : monthly_6 (factor)_cum_20 (stocks)

```{r}
quarterly_6_cum_20 <- stock_20_6_cum %>% 
  select(Id, ym)

monthly_6_cum_20 <- quarterly_6_cum_20
```


```{r}
save(monthly_6_mean_20, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/monthly_6_mean_20.RData")

save(quarterly_6_mean_20, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/quarterly_6_mean_20.RData")

save(monthly_6_cum_20, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/monthly_6_cum_20.RData")

save(quarterly_6_cum_20, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/quarterly_6_cum_20.RData")
```



## Stock List : monthly_3 (factor)_mean36_20 (stocks)
```{r}
monthly_3_mean_20 <- stock_20_3_mean36 %>% 
  select(Id, ym)

quarterly_3_mean_20 <- monthly_3_mean_20
```

## Stock List : monthly_3 (factor)_cum_20 (stocks)

```{r}
quarterly_3_cum_20 <- stock_20_3_cum %>% 
  select(Id, ym)

monthly_3_cum_20 <- quarterly_3_cum_20
```

```{r}
save(monthly_3_mean_20, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/monthly_3_mean_20.RData")

save(quarterly_3_mean_20, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/quarterly_3_mean_20.RData")

save(monthly_3_cum_20, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/monthly_3_cum_20.RData")

save(quarterly_3_cum_20, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/quarterly_3_cum_20.RData")
```



## Stock List : monthly_6 (factor)_mean36_10 (th Decile)
```{r}
quarterly_6_mean_10 <- stock_10_6_mean36 %>% 
  select(Id, ym)

monthly_6_mean_10 <-quarterly_6_mean_10
```

## Stock List : monthly_6 (factor)_cum_10 (th Decile)

```{r}
quarterly_6_cum_10 <- stock_10_6_cum %>% 
  select(Id, ym)

monthly_6_cum_10 <- quarterly_6_cum_10
```


```{r}
save(monthly_6_mean_10, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/monthly_6_mean_10.RData")

save(quarterly_6_mean_10, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/quarterly_6_mean_10.RData")

save(monthly_6_cum_10, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/monthly_6_cum_10.RData")

save(quarterly_6_cum_10, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/quarterly_6_cum_10.RData")
```



## Stock List : monthly_3 (factor)_mean36_10 (th Decile)
```{r}
quarterly_3_mean_10 <- stock_10_3_mean36 %>% 
  select(Id, ym)

monthly_3_mean_10 <-quarterly_3_mean_10
```

## Stock List : monthly_3 (factor)_cum_10 (th Decile)

```{r}
quarterly_3_cum_10 <- stock_10_3_cum %>% 
  select(Id, ym)

monthly_3_cum_10 <- quarterly_3_cum_10
```


```{r}
save(monthly_3_mean_10, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/monthly_3_mean_10.RData")

save(quarterly_3_mean_10, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/quarterly_3_mean_10.RData")

save(monthly_3_cum_10, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/monthly_3_cum_10.RData")

save(quarterly_3_cum_10, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/SS23_Empirical-Asset-Pricing/Data/Stock_List/quarterly_3_cum_10.RData")
```





## Calculate Weight
```{r}

# リターンデータを含むパネルデータセット（firm, year_month, returnなど）を準備しておく

window_size <- 36  # 過去の期間（36ヶ月）

portfolio <- data.frame()  # ポートフォリオ結果を格納するデータフレーム

# パネルデータをfirmとyear_monthでグループ化
grouped_data <- stock_list %>%
  group_by(Id, ym)

# 各月ごとに処理
for (date in unique(stock_list$ym)) {
    # 開始日を計算
  start_date <- as.Date(date) - months(window_size - 1)
  
  # 過去の期間内のデータを抽出
  window_data <- stock_list %>%
    filter(year_month >= start_date & year_month <= date)
  
  # リターンデータをリスト形式に変換
  return_list <- window_data %>%
    group_by(firm) %>%
    summarise(return = list(return)) %>%
    pull(return)
  
  # タンジェントポートフォリオの構築
  tangent_portfolio <- tangentPortfolio(return_list, method = "GMV")
  
  # ポートフォリオ結果をデータフレームに追加
  portfolio <- portfolio %>%
    bind_rows(data.frame(date = date, weights = tangent_portfolio$weights))
}

# ポートフォリオ結果を表示
print(portfolio)

```

