---
title: "Variable_Creation_June_21"
author: "Yasu and yuru"
date: '2023-06-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Library Import
```{r}
library(data.table)
library(tidyr)
library(tidyverse)
library(rollRegres)
library(roll)
library(zoo)
```

```{r}
load("~/Desktop/Summer Semester/Advanced Seminar/GBR/panel_country_May28.RData")
load("~/Desktop/Summer Semester/Advanced Seminar/GBR/DTB6_monthly.RData")
panel_country <- as.data.table(panel_country)
```

##Create regression data
###Coefficients
```{r}
#merging panel_country with DTB6_monthly(risk free rate) 
panel_reduced <- merge(panel_country[!is.na(RET.USD) & !is.na(MV.USD) & !is.infinite(RET.USD) & !is.infinite(MV.USD), c("Id", "ym", "RET.USD", "MV.USD")], DTB6_monthly[,c("ym", "DTB6")], by=c("ym"))
```

```{r}
panel_reduced[, MRET.USD:=weighted.mean(RET.USD, coalesce(MV.USD, 0), na.rm = T), by=ym]
panel_reduced[, RE.USD:=RET.USD-DTB6]
panel_reduced[, REM.USD:=MRET.USD-DTB6]
panel_reduced <- setorderv(panel_reduced, c("ym"))
```

```{r}
coef.fun <- . %>% as.data.frame %>% lm %>% .$coefficients
```

#### 1-Year

```{r}
coef_12 <- panel_reduced %>%
  group_by(Id) %>%
  do(cbind(
           select(., ym, RET.USD),
           coef = select(., RE.USD, REM.USD) %>%
             rollapplyr(12, coef.fun, by.column = FALSE, fill = NA)
           )) %>%
  ungroup
```
####3-Year
```{r}
coef_36 <- panel_reduced %>%
  group_by(Id) %>%
  do(cbind(
           select(., ym, RET.USD),
           coef = select(., RE.USD, REM.USD) %>%
             rollapplyr(36, coef.fun, by.column = FALSE, fill = NA)
           )) %>%
  ungroup
```

#### 5-Year

```{r}
coef_60 <- panel_reduced %>%
  group_by(Id) %>%
  do(cbind(
           select(., ym, RET.USD),
           coef = select(., RE.USD, REM.USD) %>%
             rollapplyr(60, coef.fun, by.column = FALSE, fill = NA)
           )) %>%
  ungroup
```

###Sigma

```{r}
resid.fun <- . %>% as.data.frame %>% lm %>% .$residuals
```

#### 1-Year

```{r}
resid_12 <- panel_reduced %>%
  group_by(Id) %>%
  do(cbind(
           select(., ym, RET.USD),
           resid = select(., RE.USD, REM.USD) %>%
             rollapplyr(12, resid.fun, by.column = FALSE, fill = NA)
           )) %>%
  ungroup
```

#### 3-Year

```{r}
resid_36 <- panel_reduced %>%
  group_by(Id) %>%
  do(cbind(
           select(., ym, RET.USD),
           resid = select(., RE.USD, REM.USD) %>%
             rollapplyr(36, resid.fun, by.column = FALSE, fill = NA)
           )) %>%
  ungroup
```


#### 5-Year
```{r}
resid_60 <- panel_reduced %>%
  group_by(Id) %>%
  do(cbind(
           select(., ym, RET.USD),
           resid = select(., RE.USD, REM.USD) %>%
             rollapplyr(60, resid.fun, by.column = FALSE, fill = NA)
           )) %>%
  ungroup
```

##Factors
###Value
####B/M
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_val<- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD","WC05476", "WC05001", "WC05202", "WC18100", "WC18198")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_val[,.N,by=Id]
panel_reduced_val <- panel_reduced_val[count_table[N>12]$Id]

#WC05001 Market Price, WC05476 Book Value per Share
#WC05001 Market Price, WC05202 Earnings per Share - Fiscal Year End
#WC18100 Enterprise value, WC18198 Earnings before Interest, Taxes, Depreciation & Amortization (EBITDA)

panel_reduced_val <- panel_reduced_val[,`B/M` := WC05476/WC05001]
panel_reduced_val <- panel_reduced_val[,`E/P` := WC05202/WC05001]
panel_reduced_val <- panel_reduced_val[,`EBITDA/EV` := WC18198/WC18100]

panel_reduced_val <- panel_reduced_val %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`)

```

####E/P
####EBITDA/EV



###Size
####Log_MV
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_lnMV<- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_lnMV[,.N,by=Id]
panel_reduced_lnMV <- panel_reduced_lnMV[count_table[N>12]$Id]

#WC05001 Market Price, WC05476 Book Value per Share
panel_reduced_lnMV <- panel_reduced_lnMV[, Log_MV := log(MV.USD)]

panel_reduced_lnMV <- panel_reduced_lnMV %>% 
  select(Id, ym, MV.USD, RET.USD, Log_MV)
```


###Momentum
####RSI
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_rsi <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_rsi[,.N,by=Id]
panel_reduced_rsi <- panel_reduced_rsi[count_table[N>12]$Id]


panel_reduced_rsi[, gain := ifelse(RET.USD>0, RET.USD, 0)]
panel_reduced_rsi[, loss := ifelse(RET.USD<0, -RET.USD, 0)]

panel_reduced_rsi[, average_gain := frollmean(gain, 12, align = "right"), by = Id]
panel_reduced_rsi[, average_loss := frollmean(loss, 12, align = "right"), by = Id]
panel_reduced_rsi[, RS := average_gain/average_loss]
panel_reduced_rsi[, RSI := 100 - (100/(1+RS))]

panel_reduced_rsi <- panel_reduced_rsi %>% 
  select(Id, ym, MV.USD, RET.USD, RSI)
```

####Alpha_1
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_alpha_1 <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_alpha_1[,.N,by=Id]
panel_reduced_alpha_1 <- panel_reduced_alpha_1[count_table[N>12]$Id]

panel_reduced_alpha_1 <- panel_reduced_alpha_1 %>%
  select(Id, ym, MV.USD) %>% 
  full_join(coef_12, by = c("Id", "ym"))

names(panel_reduced_alpha_1) <- c("Id", "ym", "MV.USD", "RET.USD", "Alpha_1", "Beta_1", "coef_1")

panel_reduced_alpha_1 <- panel_reduced_alpha_1 %>%
  select(Id, ym, MV.USD, RET.USD, Alpha_1)
```

####Alpha_3
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_alpha_3 <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_alpha_3[,.N,by=Id]
panel_reduced_alpha_3 <- panel_reduced_alpha_3[count_table[N>12]$Id]

panel_reduced_alpha_3 <- panel_reduced_alpha_3 %>%
  select(Id, ym, MV.USD) %>% 
  full_join(coef_36, by = c("Id", "ym"))

names(panel_reduced_alpha_3) <- c("Id", "ym", "MV.USD", "RET.USD", "Alpha_3", "Beta_3", "coef_3")

panel_reduced_alpha_3 <- panel_reduced_alpha_3 %>%
  select(Id, ym, MV.USD, RET.USD, Alpha_3)
```

####Alpha_5
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_alpha_5 <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_alpha_5[,.N,by=Id]
panel_reduced_alpha_5 <- panel_reduced_alpha_5[count_table[N>12]$Id]

panel_reduced_alpha_5 <- panel_reduced_alpha_5 %>%
  select(Id, ym, MV.USD) %>% 
  full_join(coef_60, by = c("Id", "ym"))

names(panel_reduced_alpha_5) <- c("Id", "ym", "MV.USD", "RET.USD", "Alpha_5", "Beta_5", "coef_5")

panel_reduced_alpha_5 <- panel_reduced_alpha_5 %>%
  select(Id, ym, MV.USD, RET.USD, Alpha_5)
```

####Momentum_12_2
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_momentum <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_momentum[,.N,by=Id]
panel_reduced_momentum <- panel_reduced_momentum[count_table[N>12]$Id]

# Define a function to find the lagged value of return for a stock
create_lag <- function(x, n) c(rep(NA, n), head(x, -n))

# Using the function to find the 12-months-ago, 11-months-ago, ~, 3 months ago return of stock 
panel_reduced_momentum[, Before2 := create_lag(RET.USD, 2), by = Id]
panel_reduced_momentum[, Before3 := create_lag(RET.USD, 3), by = Id]
panel_reduced_momentum[, Before4 := create_lag(RET.USD, 4), by = Id]
panel_reduced_momentum[, Before5 := create_lag(RET.USD, 5), by = Id]
panel_reduced_momentum[, Before6 := create_lag(RET.USD, 6), by = Id]
panel_reduced_momentum[, Before7 := create_lag(RET.USD, 7), by = Id]
panel_reduced_momentum[, Before8 := create_lag(RET.USD, 8), by = Id]
panel_reduced_momentum[, Before9 := create_lag(RET.USD, 9), by = Id]
panel_reduced_momentum[, Before10 := create_lag(RET.USD, 10), by = Id]
panel_reduced_momentum[, Before11 := create_lag(RET.USD, 11), by = Id]
panel_reduced_momentum[, Before12 := create_lag(RET.USD, 12), by = Id]

# Momentum_12_2: Past performance of stocks: use geometric mean to calculate the compound return of a stock over the past twelve months, but ignores the previous month
panel_reduced_momentum <- panel_reduced_momentum[,Mom_12_2:=((100+Before2)*(100+Before3)*(100+Before4)*(100+Before5)*(100+Before6)*(100+Before7)*(100+Before8)*(100+Before9)*(100+Before10)*(100+Before11)*(100+Before12))^(1/10)-100]


panel_reduced_momentum <- panel_reduced_momentum %>%
  select(Id, ym, MV.USD, RET.USD, Mom_12_2)
```

###Yield
####DY
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_yield<- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD","WC05101", "WC05001")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_yield[,.N,by=Id]
panel_reduced_yield <- panel_reduced_yield[count_table[N>12]$Id]

#WC05101 Dividends per Share WC05001 Market Price
#Dividend Yield = Dividends Per Share / Price Per Share
panel_reduced_yield <- panel_reduced_yield[, DY:= WC05101/WC05001*100]
panel_reduced_yield <- panel_reduced_yield %>%
  select(Id, ym, MV.USD, RET.USD, DY)
```



###Quality
####ROE
```{r}
#Select only necessary variables from the comprehensive data set 
panel_reduced_ROE <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD","WC08301")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months

count_table <- panel_reduced_ROE[,.N,by=Id]
panel_reduced_ROE <- panel_reduced_ROE[count_table[N>12]$Id]

#WC08301 Return on Equity -- Total (%)
panel_reduced_ROE <- panel_reduced_ROE[,ROE:=WC08301] 

panel_reduced_ROE <- panel_reduced_ROE %>% select(Id, ym, MV.USD, RET.USD, ROE)

```

####ROA
```{r}
#Select only necessary variables from the comprehensive data set 
panel_reduced_ROA <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD","WC08326")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months

count_table <- panel_reduced_ROA[,.N,by=Id]
panel_reduced_ROA <- panel_reduced_ROA[count_table[N>12]$Id]

#WC08326 Return on Assets
panel_reduced_ROA <- panel_reduced_ROA[,ROA:=WC08326] 

panel_reduced_ROA <- panel_reduced_ROA %>% select(Id, ym, MV.USD, RET.USD, ROA)
```

####GP/A
```{r}
#Select only necessary variables from the comprehensive data set 
panel_reduced_GPA <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD","WC08326")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months

count_table <- panel_reduced_ROA[,.N,by=Id]
panel_reduced_ROA <- panel_reduced_ROA[count_table[N>12]$Id]

#gross profit to asset
panel_reduced_ROA <- panel_reduced_ROA[,ROE:=WC08326] 

panel_reduced_ROA <- panel_reduced_ROA %>% select(Id, ym, MV.USD, RET.USD, ROA)
```

####OP/BE
```{r}
#Select only necessary variables from the comprehensive data set 
panel_reduced_ROA <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD","WC08326")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months

count_table <- panel_reduced_ROA[,.N,by=Id]
panel_reduced_ROA <- panel_reduced_ROA[count_table[N>12]$Id]

#operating profit-to-book equity
panel_reduced_ROA <- panel_reduced_ROA[,ROE:=WC08326] 

panel_reduced_ROA <- panel_reduced_ROA %>% select(Id, ym, MV.USD, RET.USD, ROA)
```

###Low Volatility
####Beta_1
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_beta_1 <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_beta_1[,.N,by=Id]
panel_reduced_beta_1 <- panel_reduced_beta_1[count_table[N>12]$Id]

panel_reduced_beta_1 <- panel_reduced_beta_1 %>%
  select(Id, ym, MV.USD) %>% 
  full_join(coef_12, by = c("Id", "ym"))

names(panel_reduced_beta_1) <- c("Id", "ym", "MV.USD", "RET.USD", "Alpha_1", "Beta_1", "coef_1")

panel_reduced_beta_1 <- panel_reduced_beta_1 %>%
  select(Id, ym, MV.USD, RET.USD, Beta_1)
```

####Beta_3
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_beta_3 <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_beta_3[,.N,by=Id]
panel_reduced_beta_3 <- panel_reduced_beta_3[count_table[N>12]$Id]

panel_reduced_beta_3 <- panel_reduced_beta_3 %>%
  select(Id, ym, MV.USD) %>% 
  full_join(coef_36, by = c("Id", "ym"))

names(panel_reduced_beta_3) <- c("Id", "ym", "MV.USD", "RET.USD", "Alpha_3", "Beta_3", "coef_3")

panel_reduced_beta_3 <- panel_reduced_beta_3 %>%
  select(Id, ym, MV.USD, RET.USD, Beta_3)
```

####Beta_5
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_beta_5 <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_beta_5[,.N,by=Id]
panel_reduced_beta_5 <- panel_reduced_beta_5[count_table[N>12]$Id]

panel_reduced_beta_5 <- panel_reduced_beta_5 %>%
  select(Id, ym, MV.USD) %>% 
  full_join(coef_60, by = c("Id", "ym"))

names(panel_reduced_beta_5) <- c("Id", "ym", "MV.USD", "RET.USD", "Alpha_5", "Beta_5", "coef_1")

panel_reduced_beta_5 <- panel_reduced_beta_5 %>%
  select(Id, ym, MV.USD, RET.USD, Beta_5)
```

####Sigma_1
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_sigma_1 <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_sigma_1[,.N,by=Id]
panel_reduced_sigma_1 <- panel_reduced_sigma_1[count_table[N>12]$Id]

panel_reduced_sigma_1 <- panel_reduced_sigma_1 %>%
  select(Id, ym, MV.USD) %>% 
  full_join(resid_12, by = c("Id", "ym")) %>% 
  select(Id, ym, MV.USD, RET.USD, `resid.12`)

names(panel_reduced_sigma_1) <- c("Id", "ym", "MV.USD", "RET.USD", "Sigma_1")

panel_reduced_sigma_1 <- panel_reduced_sigma_1 %>%
  select(Id, ym, MV.USD, RET.USD, Sigma_1)
```

####Sigma_3
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_sigma_3 <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_sigma_3[,.N,by=Id]
panel_reduced_sigma_3<- panel_reduced_sigma_3[count_table[N>12]$Id]

panel_reduced_sigma_3 <- panel_reduced_sigma_3 %>%
  select(Id, ym, MV.USD) %>% 
  full_join(resid_36, by = c("Id", "ym")) %>% 
  select(Id, ym, MV.USD, RET.USD, `resid.36`)

names(panel_reduced_sigma_3) <- c("Id", "ym", "MV.USD", "RET.USD", "Sigma_3")

panel_reduced_sigma_3 <- panel_reduced_sigma_3 %>%
  select(Id, ym, MV.USD, RET.USD, Sigma_3)
```

####Sigma_5
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_sigma_5 <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_sigma_5[,.N,by=Id]
panel_reduced_sigma_5<- panel_reduced_sigma_5[count_table[N>12]$Id]

panel_reduced_sigma_5 <- panel_reduced_sigma_5 %>%
  select(Id, ym, MV.USD) %>% 
  full_join(resid_60, by = c("Id", "ym")) %>% 
  select(Id, ym, MV.USD, RET.USD, `resid.60`)

names(panel_reduced_sigma_5) <- c("Id", "ym", "MV.USD", "RET.USD", "Sigma_5")

panel_reduced_sigma_5 <- panel_reduced_sigma_5 %>%
  select(Id, ym, MV.USD, RET.USD, Sigma_5)
```

####SD
```{r}
#Monthly standard deviation
panel_reduced_sd <- panel_reduced %>%
  group_by(Id)%>%
  mutate(SD=rollapply(RET.USD,12,sd,align='right',fill=NA)) %>%
  ungroup %>% 
  select(Id, ym, MV.USD, RET.USD, SD)
```

###liquidity
####T/O
```{r}
#Check the number of outstanding data
trad <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD","WC05651", "WC05301", "WC08006")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months

count_table <- trad[,.N,by=Id]
trad <- trad[count_table[N>12]$Id]
```

```{r}
#Select only necessary variables from the comprehensive data set 
panel_reduced_TO <- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD","WC05651", "WC05301")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months

count_table <- panel_reduced_TO[,.N,by=Id]
panel_reduced_TO <- panel_reduced_TO[count_table[N>12]$Id]

#WC05651 Common Shares Traded - Annual #WC05301 Common Shares Outstanding
panel_reduced_TO <- panel_reduced_TO[,Lagged_Out := shift(WC05301, n = 12)]
panel_reduced_TO[,Avg_Out := (WC05301 + Lagged_Out)/2]
panel_reduced_TO <- panel_reduced_TO[, `T/O`:=WC05651/Avg_Out] 

panel_reduced_TO <- panel_reduced_TO %>% select(Id, ym, MV.USD, RET.USD, `T/O`)
```

###Growth
####EPS
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_eps<- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD","WC05202")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_eps[,.N,by=Id]
panel_reduced_eps <- panel_reduced_eps[count_table[N>12]$Id]

#WC05202 EPS, WC05508 SPS
panel_reduced_eps <- panel_reduced_eps %>% 
  mutate(Lagged_EPS = shift(WC05202, n = 12)) %>%
  mutate(Growth_Rate_EPS = (WC05202 - Lagged_EPS) / Lagged_EPS *100)

panel_reduced_eps <- panel_reduced_eps %>% 
  select(Id, ym, MV.USD, RET.USD, Growth_Rate_EPS)

names(panel_reduced_eps) <- c("Id","ym","MV.USD","RET.USD", "EPS")
```

####SPS
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_sps<- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD", "WC05508")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_sps[,.N,by=Id]
panel_reduced_sps <- panel_reduced_sps[count_table[N>12]$Id]

#WC05508 SPS
panel_reduced_sps <- panel_reduced_sps %>% 
  mutate(Lagged_SPS = shift(WC05508, n = 12)) %>%
  mutate(Growth_Rate_SPS = (WC05508 - Lagged_SPS) / Lagged_SPS *100)

panel_reduced_sps <- panel_reduced_sps %>% 
  select(Id, ym, MV.USD, RET.USD, Growth_Rate_SPS)

names(panel_reduced_sps) <- c("Id","ym","MV.USD","RET.USD", "SPS")
```

###Others
####MV
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_MV<- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_MV[,.N,by=Id]
panel_reduced_MV <- panel_reduced_MV[count_table[N>12]$Id]

panel_reduced_MV <- panel_reduced_MV %>% 
  mutate(MV = MV.USD)
```

####AG
```{r}
# Select only necessary variables from the comprehensive data set
panel_reduced_inv<- panel_country[!is.na(RET.USD),c("Id","ym","MV.USD","RET.USD","WC02999")]

# Find the length of history of each stock, and filter out stocks that has a history less than 12 months
count_table <- panel_reduced_inv[,.N,by=Id]
panel_reduced_inv <- panel_reduced_inv[count_table[N>12]$Id]

#WC02999 Total Assets
panel_reduced_inv <- panel_reduced_inv %>% 
  mutate(Lagged_Asset = shift(WC02999, n = 12)) %>%
  mutate(AG = (WC02999 - Lagged_Asset) / Lagged_Asset *100) %>% 
  select(-Lagged_Asset)

panel_reduced_inv <- panel_reduced_inv %>% 
  select(Id, ym, MV.USD, RET.USD, AG)
```
####I/A

####NSI


##Facotr Data FF5
```{r}
##Factor data for FF5
names(coef_36) <-  c("Id", "ym", "RET.USD", "alpha_36", "beta_36", "coef_36")

Factor_data_ff5 <- coef_36 %>% 
  select(Id, ym, beta_36) %>%
  full_join(panel_reduced_val, by = c("Id", "ym")) %>% 
  select(Id, ym, MV.USD, RET.USD, beta_36, `B/M`) %>% 
  full_join(panel_reduced_ROE, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, beta_36, `B/M`, ROE) %>% 
  full_join(panel_reduced_inv, by = c("Id", "ym", "MV.USD", "RET.USD")) %>%
  select(Id, ym, MV.USD, RET.USD, beta_36, `B/M`, ROE, AG) %>% 
  full_join(panel_reduced_momentum, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, RET.USD, beta_36, MV.USD, `B/M`, ROE, AG, Momentum_12_2)

names(Factor_data_ff5) <- c("Id", "ym", "RET.USD", "Beta_3", "MV", "`B/M`", "ROE", "AG", "Mom_12_2")
```

```{r}
save(Factor_data_ff5, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/Factor_data_FF5.RData")
```  
  
  
##Factor data
```{r}
Factor_data <- panel_reduced_val %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`) %>% 
  full_join(panel_reduced_lnMV, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV) %>% 
  full_join(panel_reduced_rsi, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI) %>% 
  full_join(panel_reduced_alpha_1, by = c("Id", "ym", "MV.USD", "RET.USD")) %>%
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1) %>%
  full_join(panel_reduced_alpha_3, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3) %>% 
  full_join(panel_reduced_alpha_5, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5) %>% 
  full_join(panel_reduced_momentum, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2) %>% 
  full_join(panel_reduced_yield ,by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY) %>% 
  full_join(panel_reduced_ROE ,by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE) %>% 
  full_join(panel_reduced_ROA ,by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA) %>% 
  full_join(panel_reduced_beta_1 ,by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1) %>% 
  full_join(panel_reduced_beta_3 ,by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1, Beta_3) %>% 
  full_join(panel_reduced_beta_5, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA,Beta_1, Beta_3, Beta_5) %>% 
  full_join(panel_reduced_sigma_1, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1, Beta_3, Beta_5, Sigma_1) %>% 
  full_join(panel_reduced_sigma_3, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1, Beta_3, Beta_5, Sigma_1, Sigma_3) %>% 
  full_join(panel_reduced_sigma_5, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1, Beta_3, Beta_5, Sigma_1, Sigma_3, Sigma_5) %>%
  full_join(panel_reduced_sd, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1, Beta_3, Beta_5, Sigma_1, Sigma_3, Sigma_5, SD) %>% 
  full_join(panel_reduced_TO, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1, Beta_3, Beta_5, Sigma_1, Sigma_3, Sigma_5, SD, `T/O`) %>% 
  full_join(panel_reduced_eps, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1, Beta_3, Beta_5, Sigma_1, Sigma_3, Sigma_5, SD, `T/O`, EPS) %>% 
  full_join(panel_reduced_sps, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1, Beta_3, Beta_5, Sigma_1, Sigma_3, Sigma_5, SD, `T/O`, EPS, SPS)%>% 
  full_join(panel_reduced_MV, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, MV.USD, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1, Beta_3, Beta_5, Sigma_1, Sigma_3, Sigma_5, SD, `T/O`, EPS, SPS, MV) %>% 
  full_join(panel_reduced_inv, by = c("Id", "ym", "MV.USD", "RET.USD")) %>% 
  select(Id, ym, RET.USD, `B/M`, `E/P`, `EBITDA/EV`, Log_MV, RSI, Alpha_1, Alpha_3, Alpha_5, Mom_12_2, DY, ROE, ROA, Beta_1, Beta_3, Beta_5, Sigma_1, Sigma_3, Sigma_5, SD, `T/O`, EPS, SPS, MV, AG)
```

```{r}
save(Factor_data, file = "/Users/kojimadamsimith/Desktop/Summer Semester/Advanced Seminar/GBR/Factor_data.RData")
```