---
title: "Visualize cumulative performance"
author: "Yu"
date: "2023-07-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Common portfolio risk measures
# annualled return
# standard deviation
#expected shortfall
#value at risk
#component contribution
#maximum drawdown 
#sharpe ratio




## common benchmark relative performance measures
#information ratio
#tracking error
#excess return
#maximum relative drawdown

```{r}
library(zoo)
library(quadprog)
library(IntroCompFinR)
library(tidyr)
library(dplyr)
library(lubridate)
library(data.table)
library(ggplot2)
library(tibble)
library(PerformanceAnalytics)
library(xts)
```


## Change the data format
### weighted_result_quarterly_3_mean_20
```{r}
weighted_result_quarterly_3_mean_20_complete <- weighted_result_quarterly_3_mean_20 %>%
  mutate(ym=rownames(weighted_result_quarterly_3_mean_20)) %>%
  mutate(ym=as.Date(ym, "%Y-%m-%d")) %>%
  select(ym, everything()) %>%
  mutate_all(~replace(., is.na(.), -Inf)) %>%
  complete(ym = seq.Date(min(ym), as.Date("2021-12-01"), by="month")) %>%
  fill(names(.), .direction= "down") %>%
  mutate_all(~replace(., is.infinite(.), NA)) %>%
  mutate(ym=format(ym, format="%Y-%m-%d"))
```

###quarterly_3_mean_20
```{r}
t5 <- weighted_result_quarterly_3_mean_20_complete %>% 
  pivot_longer(cols = -ym, names_to = "Id", values_to = "weight")

class(t5$ym)

class(DS.monthly$ym)
t5$ym <- as.yearmon(t5$ym)

t6 <- DS.monthly %>%
  full_join(t5, by = c("Id", "ym")) %>% 
  select(Id, ym, weight, RET.USD)

t7 <- t6 %>% 
  filter(!is.na(weight) & !is.na(RET.USD)) %>% 
  arrange(ym)

quarterly_3_mean_performance <- t7 %>% 
  group_by(ym) %>% 
  summarise(RET = sum(weight * RET.USD)) %>% 
  ungroup

print(mean(quarterly_3_mean_performance$RET))
print(sd(quarterly_3_mean_performance$RET))
print(mean(quarterly_3_mean_performance$RET)/sd(quarterly_3_mean_performance$RET))

#convert monthly data to annual date

quarterly_3_mean_performance$ym <- as.Date(as.yearmon(quarterly_3_mean_performance$ym,"%Y.%m"))

quarterly_3_mean_performance$RET <- quarterly_3_mean_performance$RET/100

annual_returns_xts <- period.apply(quarterly_3_mean_performance, endpoints(quarterly_3_mean_performance, "years"), FUN = function(x) prod(1 + x) - 1)

print(mean(annual_returns_xts$RET))
print(sd(annual_returns_xts$RET))
print(mean(annual_returns_xts$RET)/sd(annual_returns_xts$RET))
```


```{r}
#Plot
ggplot(quarterly_3_mean_performance, aes(x = ym, y = RET)) +
  geom_line() +
  labs(x = "ym", y = "Return") +
  ggtitle("quarterly_3_mean_20")


# Turnover
Turnover_3_mean <- t5 %>% 
  mutate(weight = replace_na(weight, 0)) %>%
  arrange(Id, ym) %>% 
  group_by(Id) %>%
  mutate(weight_1 = lead(weight)) %>% 
  ungroup

Turnover_3_mean <- Turnover_3_mean %>% 
  mutate(abs = abs(weight_1 - weight))%>% 
  group_by(ym) %>% 
  summarise(sigma = sum(abs))%>% 
  mutate(sigma = replace_na(sigma, 0))

print(sum(Turnover_3_mean$sigma))
print(n_distinct(Turnover_3_mean$ym))
print(sum(Turnover_3_mean$sigma)/n_distinct(Turnover_3_mean$ym)/2)


# Effectiv N 
Effectiv_N_3_mean <- t7 %>% 
  mutate(w2 = weight^2)%>% 
  group_by(ym) %>% 
  summarise(sigma = sum(w2)) %>% 
  mutate(sigma_i = sigma^(-1))

print(sum(Effectiv_N_3_mean$sigma_i)/n_distinct(Effectiv_N_3_mean$ym))
```


```{r}

#annualized
#converted to time series data

quarterly_3_mean_performance$ym <- as.Date(as.yearmon(quarterly_3_mean_performance$ym,"%Y.%m"))

tseri_quarterly_3_mean_performance <- quarterly_3_mean_performance[,2]
rownames(tseri_quarterly_3_mean_performance) <- quarterly_3_mean_performance$ym

# Compute the annualized mean
annual_tseri_quarterly_3_mean_performance <- Return.annualized(tseri_quarterly_3_mean_performance,scale = 12, geometric = FALSE)
annual_tseri_quarterly_3_mean_performance

# Compute the annualized standard deviation
StdDev.annualized(sp500_returns)

# Compute the annualized Sharpe ratio
ann_sharpe <- Return.annualized(sp500_returns) / StdDev.annualized(sp500_returns)

# Convert monthly data to annual data
annual_returns_xts <- period.apply(quarterly_3_mean_performance, endpoints(quarterly_3_mean_performance, "years"), FUN = function(x) prod(1 + x) - 1)



```
```{r}
# cumulative return
cumu_quarterly_3_mean_performance <- cumsum(tseri_quarterly_3_mean_performance)
rownames(cumu_quarterly_3_mean_performance) <- quarterly_3_mean_performance$ym

write.csv(cumu_quarterly_3_mean_performance,file = "../Performance/visual_annual&cumulative_result/3_mean_cumulative_return.csv")

#charts.TimeSeries(cumu_quarterly_3_mean_performance,auto.grid = TRUE,xlab = #"Time",ylab = "Cumulative Return", main = "3_mean_Cumulative Return Plot")

```

