---
title: "Plot Return"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(ggplot2)
theme_set(theme_minimal())
```

```{r}
library(readr)
X3_cum_cumulative_return <- read_csv("Performance/visual_annual&cumulative_result/3_cum_cumulative_return.csv", 
    col_types = cols(...1 = col_date(format = "%Y-%m-%d")))
X3_cum_cumulative_return <- X3_cum_cumulative_return %>%
  rename(X3_cum_cumulative_return=RET, date=`...1`)

X3_var_cumulative_return <- read_csv("Performance/visual_annual&cumulative_result/3_var_cumulative_return.csv", 
    col_types = cols(...1 = col_date(format = "%Y-%m-%d")))
X3_var_cumulative_return <- X3_var_cumulative_return %>%
  rename(X3_var_cumulative_return=RET, date=`...1`)
```

```{r}
merge.data <- merge(X3_cum_cumulative_return, X3_var_cumulative_return, all=TRUE)

plot.data <- merge.data %>%
  select(date, X3_cum_cumulative_return, X3_var_cumulative_return) %>%
  gather(key = "variable", value = "value", -date)
```

```{r}
ggplot(plot.data, aes(x = date, y = value)) + 
  geom_line(aes(color = variable, linetype = variable)) + 
  scale_color_manual(values = c("darkred", "steelblue"))
```

```{r}
load("../Univariate_Sort_Set.RData")
Univariate_Sort_Set <- as.data.table(Univariate_Sort_Set)
stock_size <- Univariate_Sort_Set
setorder(stock_size, ym, -MV.USD)
stock_big <- stock_size[!is.na(MV.USD), .(big = ifelse(((cumsum(MV.USD)/sum(MV.USD))>=0.9), 0, 1), Id), by=ym]
stock_big <- stock_big[big==1, c("Id", "ym")]
Univariate_Sort_Set_big <- merge(stock_big, Univariate_Sort_Set)
```

```{r}
Market_RET <- Univariate_Sort_Set_big %>% 
  select(Id, ym, RET.USD, MV.USD) %>% 
  group_by(ym) %>% 
  mutate(MRET = weighted.mean(RET.USD, coalesce(MV.USD, 0), na.rm = T)) %>% 
  ungroup %>% 
  arrange(ym, Id)

Market_RET_ym <- Market_RET %>% 
  group_by(ym) %>% 
  summarise(Market_RET = mean(MRET))

Market_RET_ym <- Market_RET_ym %>% 
  mutate(Market_RET = Market_RET*0.01)
```

```{r}
annual_market_ret <- Market_RET_ym %>%
  mutate(ym=as.yearmon(ym, "%Y.%m"), year=year(ym), RET.USD_PLUS_1=Market_RET + 1) %>%
  group_by(year) %>%
    summarise(PROD=prod(RET.USD_PLUS_1)) %>%
  ungroup() %>%
  mutate(ANNUAL_MKT_RET.USD=(PROD-1)*100) %>%
  select(year, ANNUAL_MKT_RET.USD)
```

```{r}
save(annual_market_ret, file = "../Data/annual_market_ret.RData")
```





