---
title: "visual_cumu_6_cum_20"
author: "Yu"
date: "2023-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
library(dplyr)
library(xts)
```


## Change the data format
### weighted_result_quarterly_6_cum_20
```{r}

weighted_result_quarterly_6_cum_20_complete <- weighted_result_quarterly_6_cum_20 %>%
  mutate(ym=rownames(weighted_result_quarterly_6_cum_20)) %>%
  mutate(ym=as.Date(ym, "%Y-%m-%d")) %>%
  select(ym, everything()) %>%
  mutate_all(~replace(., is.na(.), -Inf)) %>%
  complete(ym = seq.Date(min(ym), as.Date("2021-12-01"), by="month")) %>%
  fill(names(.), .direction= "down") %>%
  mutate_all(~replace(., is.infinite(.), NA)) %>%
  mutate(ym=format(ym, format="%Y-%m-%d"))
```

###quarterly_3_mean_20
```{r}
t5 <- weighted_result_quarterly_6_cum_20_complete %>% 
  pivot_longer(cols = -ym, names_to = "Id", values_to = "weight")

class(t5$ym)

class(DS.monthly$ym)
t5$ym <- as.yearmon(t5$ym)

t6 <- DS.monthly %>%
  full_join(t5, by = c("Id", "ym")) %>% 
  select(Id, ym, weight, RET.USD)

t7 <- t6 %>% 
  filter(!is.na(weight) & !is.na(RET.USD)) %>% 
  arrange(ym)

quarterly_6_cum_performance <- t7 %>% 
  group_by(ym) %>% 
  summarise(RET = sum(weight * RET.USD)) %>% 
  ungroup

# monthly characteristic
print(mean(quarterly_6_cum_performance$RET))
print(sd(quarterly_6_cum_performance$RET))
print(mean(quarterly_6_cum_performance$RET)/sd(quarterly_6_cum_performance$RET))

print("annual")

#convert monthly data to annual date

quarterly_6_cum_performance$ym <- as.Date(as.yearmon(quarterly_6_cum_performance$ym,"%Y.%m"))

quarterly_6_cum_performance$RET <- quarterly_6_cum_performance$RET/100

annual_cum_6_returns <- period.apply(quarterly_6_cum_performance, endpoints(quarterly_6_cum_performance, "years"), FUN = function(x) prod(1 + x) - 1)

write.csv(annual_cum_6_returns,file = "annual_cum_6_returns.csv")

print(mean(annual_cum_6_returns$RET))
print(sd(annual_cum_6_returns$RET))
print(mean(annual_cum_6_returns$RET)/sd(annual_cum_6_returns$RET))
```
```{r}

annual_cum_6_returns

#Expected Shortfall (ES):
confidence_level <- 0.05
Expected_Shortfall <- quantile(annual_cum_6_returns$RET, confidence_level, type = 1)
Expected_Shortfall

#Value at Risk (VaR):
VaR <- quantile(annual_cum_6_returns$RET, confidence_level, type = 1)
VaR 

#Component Contribution:
#component_contributions <- annual_cum_6_returns$weights * #annual_6_cum_performance$component_ret

max_drawdown <- maxDrawdown(annual_6_cum_performance$ANNUAL_RET.USD)
```


```{r}
#annual_6_cum_performance <- quarterly_6_cum_performance %>%
#  mutate(year=year(dates), RET.USD_PLUS_1=RET + 1) %>%
#  group_by(year) %>%
#    summarise(PROD=prod(RET.USD_PLUS_1)) %>%
#  ungroup() %>%
#  mutate(ANNUAL_RET.USD=(PROD-1)*100)
#annual_6_cum_performance <- period.apply(annual_6_cum_performance, endpoints(annual_6_cum_performance, #"years"), FUN = function(x) prod(1 + x) - 1)

```


```{r}

#annualized
#converted to time series data


quarterly_6_cum_performance$ym <- as.Date(as.yearmon(quarterly_6_cum_performance$ym,"%Y.%m"))

datelist <- as.list(quarterly_6_cum_performance$ym)

tseri_quarterly_6_cum_performance <- quarterly_6_cum_performance[,2]
rownames(tseri_quarterly_6_cum_performance) <- quarterly_6_cum_performance$ym

annual_tseri_quarterly_6_cum_performance <- Return.annualized(tseri_quarterly_6_cum_performance,scale = 12, geometric = FALSE)
annual_tseri_quarterly_6_cum_performance

StdDev.annualized(tseri_quarterly_6_cum_performance)

```
```{r}
# cumulative return
cumu_quarterly_6_cum_performance <- cumsum(tseri_quarterly_6_cum_performance)
rownames(cumu_quarterly_6_cum_performance) <- quarterly_6_cum_performance$ym

write.csv(cumu_quarterly_6_cum_performance,file = "6_cum_cumulative_return.csv")

#charts.TimeSeries(cumu_quarterly_3_cum_performance,auto.grid = TRUE,xlab = "Time",ylab = "Cumulative Return", main = "3_mean_Cumulative Return Plot")

```