---
title: "visual_cumu_3_var_20"
author: "Yu"
date: "2023-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(zoo)
library(quadprog)
library(IntroCompFinR)
library(tidyr)
library(dplyr)
library(lubridate)
library(data.table)
library(ggplot2)
library(tibble)
library(PerformanceAnalytics)
```


## Change the data format
### weighted_result_quarterly_3_var_20
```{r}

weighted_result_quarterly_3_var_20_complete <- weighted_result_quarterly_3_var_20 %>%
  mutate(ym=rownames(weighted_result_quarterly_3_var_20)) %>%
  mutate(ym=as.Date(ym, "%Y-%m-%d")) %>%
  select(ym, everything()) %>%
  mutate_all(~replace(., is.na(.), -Inf)) %>%
  complete(ym = seq.Date(min(ym), as.Date("2021-12-01"), by="month")) %>%
  fill(names(.), .direction= "down") %>%
  mutate_all(~replace(., is.infinite(.), NA)) %>%
  mutate(ym=format(ym, format="%Y-%m-%d"))
```

###quarterly_3_var_20
```{r}
t5_3_var_20 <- weighted_result_quarterly_3_var_20_complete %>% 
  pivot_longer(cols = -ym, names_to = "Id", values_to = "weight")

class(t5_3_var_20$ym)

class(DS.monthly$ym)
t5_3_var_20$ym <- as.yearmon(t5_3_var_20$ym)

t6_3_var_20 <- DS.monthly %>%
  full_join(t5_3_var_20, by = c("Id", "ym")) %>% 
  select(Id, ym, weight, RET.USD)

t7_3_var_20 <- t6_3_var_20 %>% 
  filter(!is.na(weight) & !is.na(RET.USD)) %>% 
  arrange(ym) 


quarterly_3_var_performance <- t7_3_var_20  %>% 
  group_by(ym) %>% 
  summarise(RET = sum(weight * RET.USD)) %>% 
  ungroup %>% filter(ym >= "1990-01-01")

# expected return
print(mean(quarterly_3_var_performance$RET))
# volatility
print(sd(quarterly_3_var_performance$RET))
# sharpe ratio
print(mean(quarterly_3_var_performance$RET)/sd(quarterly_3_var_performance$RET))

write.csv(quarterly_3_var_performance, file = "var_3_performance.csv")

#annualized_return
anualized_return <- (1+mean(quarterly_3_var_performance$RET) *0.01)^12-1
print(anualized_return)
```


```{r}

```


```{r}
#cumulative return
quarterly_3_var_performance$ym <- as.Date(as.yearmon(quarterly_3_var_performance$ym,"%Y.%m"))

tseri_quarterly_3_var_performance <- quarterly_3_var_performance[,2]
rownames(tseri_quarterly_3_var_performance) <- quarterly_3_var_performance$ym
cumu_quarterly_3_var_performance <- cumsum(tseri_quarterly_3_var_performance)

rownames(cumu_quarterly_3_var_performance) <- quarterly_3_var_performance$ym
write.csv(cumu_quarterly_3_var_performance,file = "3_var_cumulative_return.csv")
```


```{r}

# Turnover
Turnover_3_var <- t5_3_var_20 %>% 
  mutate(weight = replace_na(weight, 0)) %>%
  arrange(Id, ym) %>% 
  group_by(Id) %>%
  mutate(weight_1 = lead(weight)) %>% 
  ungroup

Turnover_3_var <- Turnover_3_var %>% 
  mutate(abs = abs(weight_1 - weight))%>% 
  group_by(ym) %>% 
  summarise(sigma = sum(abs))%>% 
  mutate(sigma = replace_na(sigma, 0))

print(sum(Turnover_3_var$sigma))
print(n_distinct(Turnover_3_var$ym))
print(sum(Turnover_3_var$sigma)/n_distinct(Turnover_3_var$ym)/2)


# Effectiv N 
Effectiv_N_3_var <- t7_3_var_20 %>% 
  mutate(w2 = weight^2)%>% 
  group_by(ym) %>% 
  summarise(sigma = sum(w2)) %>% 
  mutate(sigma_i = sigma^(-1))

print(sum(Effectiv_N_3_var$sigma_i)/n_distinct(Effectiv_N_3_var$ym))

# value at risk
confidence_level <- 0.95
VaR <- quantile(quarterly_3_var_performance$RET, 1 - confidence_level)
print(VaR)
```


```{r}
#convert monthly data to annual date

#quarterly_3_cum_performance$ym <- #as.Date(as.yearmon(quarterly_3_cum_performance$ym,"%Y.%m"))

#quarterly_3_cum_performance$RET <- quarterly_3_cum_performance$RET/100

#annual_returns_xts <- period.apply(quarterly_3_cum_performance, #endpoints(quarterly_3_cum_performance, "years"), FUN = function(x) prod(1 + x) - 1)

#print(mean(annual_returns_xts$RET))
#print(sd(annual_returns_xts$RET))
#print(mean(annual_returns_xts$RET)/sd(annual_returns_xts$RET))

```


```{r}

#annualized
#converted to time series data

quarterly_3_cum_performance$ym <- as.Date(as.yearmon(quarterly_3_cum_performance$ym,"%Y.%m"))

tseri_quarterly_3_cum_performance <- quarterly_3_cum_performance[,2]
rownames(tseri_quarterly_3_cum_performance) <- quarterly_3_cum_performance$ym

annual_tseri_quarterly_3_cum_performance <- Return.annualized(tseri_quarterly_3_cum_performance,scale = 12, geometric = TRUE)
annual_tseri_quarterly_3_cum_performance


```
```{r}
# cumulative return

#cumu_quarterly_3_cum_performance <- cumsum(tseri_quarterly_3_cum_performance)
#rownames(cumu_quarterly_3_cum_performance) <- quarterly_3_cum_performance$ym
#write.csv(cumu_quarterly_3_cum_performance,file = "3_var_cumulative_return.csv")

#charts.TimeSeries(cumu_quarterly_3_cum_performance,auto.grid = TRUE,xlab = "Time",ylab = "Cumulative Return", main = "3_var_Cumulative Return Plot")

```
