---
title: "Hanauer's Method"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(tidyr)
library(zoo)
library(dplyr)
```

#Lewellen Data

```{r}
load("Univariate_Sort_Set.RData")
Univariate_Sort_Set <- as.data.table(Univariate_Sort_Set)
stock_size <- Univariate_Sort_Set
setorder(stock_size, ym, -MV.USD)
stock_big_small <- stock_size[!is.na(MV.USD), .(big_small = ifelse(((cumsum(MV.USD)/sum(MV.USD))>=0.97), 0, 1), Id), by=ym]
stock_big_small <- stock_big_small[big_small==1, c("Id", "ym")]
Univariate_Sort_Set_big_small <- merge(stock_big_small, Univariate_Sort_Set)
```

##Cross-Sectional Regression

```{r}
coef_cross_sectional_new <- Univariate_Sort_Set_big_small[!is.na(Sigma_3) & !is.infinite(Sigma_3) & !is.na(`B/Mm`) & !is.infinite(`B/Mm`) & !is.na(CEI) & !is.infinite(CEI) & !is.na(Log_MV) & !is.infinite(Log_MV) & !is.na(Alpha_3) & !is.infinite(Alpha_3) & !is.na(RSI) & !is.infinite(RSI),
                                            .(intercept=lm(ExRET.USD~Sigma_3+`B/Mm`+CEI+Log_MV+Alpha_3+RSI)$coefficient[1],
                                              gamma.sigma3=lm(ExRET.USD~Sigma_3+`B/Mm`+CEI+Log_MV+Alpha_3+RSI)$coefficient[2],
                                              gamma.bmm=lm(ExRET.USD~Sigma_3+`B/Mm`+CEI+Log_MV+Alpha_3+RSI)$coefficient[3],
                                              gamma.cei=lm(ExRET.USD~Sigma_3+`B/Mm`+CEI+Log_MV+Alpha_3+RSI)$coefficient[4],
                                              gamma.logmv=lm(ExRET.USD~Sigma_3+`B/Mm`+CEI+Log_MV+Alpha_3+RSI)$coefficient[5],
                                              gamma.alpha3=lm(ExRET.USD~Sigma_3+`B/Mm`+CEI+Log_MV+Alpha_3+RSI)$coefficient[6],
                                              gamma.rsi=lm(ExRET.USD~Sigma_3+`B/Mm`+CEI+Log_MV+Alpha_3+RSI)$coefficient[7])
                              ,by=ym]
```

##T-Test

```{r}
# coef_cross_sectional_new[,t.test(intercept)]
# coef_cross_sectional_new[,t.test(gamma.sigma3)]
# coef_cross_sectional_new[,t.test(gamma.bmm)]
# coef_cross_sectional_new[,t.test(gamma.cei)]
# coef_cross_sectional_new[,t.test(gamma.logmv)]
# coef_cross_sectional_new[,t.test(gamma.alpha3)]
# coef_cross_sectional_new[,t.test(gamma.rsi)]
```

##Rolling Mean and Cumulative Mean

```{r}
cols <- colnames(coef_cross_sectional_new[, -1])
setorder(coef_cross_sectional_new, ym)
data_lewellen <- cbind(coef_cross_sectional_new, mean36 = rollmeanr(coef_cross_sectional_new[, ..cols], 36, fill = NA))
data_lewellen <- cbind(data_lewellen, cummean = cumsum(coef_cross_sectional_new[, ..cols]) / seq_along(data_lewellen[, ym]))
```

```{r}
# save(data_lewellen, file="Data_Lewellen.RData")
```

#Lewellen

```{r}
# merge with firm characteristics
data_set <- Univariate_Sort_Set_big_small %>% 
  select(Id, ym, MV.USD, RET.USD, MRP.USD, ExRET.USD, Sigma_3, `B/Mm`, CEI, Log_MV, Alpha_3, RSI)

lewellen_data_set <- merge(x=data_set, y=data_lewellen, by.x = c("ym"), by.y = c("ym"), all= 1)


# Creating the lag variable of mean36 average slope
lewellen_data_set[, Lag_mean36_Intercept := shift(mean36.intercept, n= 1), by = Id]
lewellen_data_set[, Lag_mean36_Sigma3 := shift(mean36.gamma.sigma3, n= 1), by = Id]
lewellen_data_set[, Lag_mean36_BMm := shift(mean36.gamma.bmm, n= 1), by = Id]
lewellen_data_set[, Lag_mean36_CEI := shift(mean36.gamma.cei, n= 1), by = Id]
lewellen_data_set[, Lag_mean36_Log_MV := shift(mean36.gamma.logmv, n= 1), by = Id]
lewellen_data_set[, Lag_mean36_Alpha3 := shift(mean36.gamma.alpha3, n= 1), by = Id]
lewellen_data_set[, Lag_mean36_RSI := shift(mean36.gamma.rsi, n= 1), by = Id]

# Creating the lag variable of cumulated average slope
lewellen_data_set[, Lag_cum_Intercept := shift(cummean.intercept, n= 1), by = Id]
lewellen_data_set[, Lag_cum_Sigma3 := shift(cummean.gamma.sigma3, n= 1), by = Id]
lewellen_data_set[, Lag_cum_BMm := shift(cummean.gamma.bmm, n= 1), by = Id]
lewellen_data_set[, Lag_cum_CEI := shift(cummean.gamma.cei, n= 1), by = Id]
lewellen_data_set[, Lag_cum_Log_MV := shift(cummean.gamma.logmv, n= 1), by = Id]
lewellen_data_set[, Lag_cum_Alpha3 := shift(cummean.gamma.alpha3, n= 1), by = Id]
lewellen_data_set[, Lag_cum_RSI := shift(cummean.gamma.rsi, n= 1), by = Id]

lewellen_expected_return_mean36 <- lewellen_data_set %>% 
  group_by(ym, Id) %>% 
  mutate(Expected_Return_36 = Lag_mean36_Intercept * intercept + Lag_mean36_Sigma3 * Sigma_3 + Lag_mean36_BMm * `B/Mm` + Lag_mean36_CEI * CEI + Lag_mean36_Log_MV * Log_MV + Lag_mean36_Alpha3 * Alpha_3 + Lag_mean36_RSI * RSI) %>% 
    ungroup

lewellen_expected_return_cummean <- lewellen_data_set %>% 
  group_by(ym, Id) %>% 
  mutate(Expected_Return_cummean = Lag_cum_Intercept * intercept + Lag_cum_Sigma3 * Sigma_3 + Lag_cum_BMm * `B/Mm` + Lag_cum_CEI * CEI + Lag_cum_Log_MV * Log_MV + Lag_cum_Alpha3 * Alpha_3 + Lag_cum_RSI * RSI) %>% 
    ungroup
```

##Returns based on mean36

```{r}
lewellen_expected_return_mean36 <- data.table(lewellen_expected_return_mean36)

setorder(lewellen_expected_return_mean36,ym,Expected_Return_36)

lewellen_expected_return_mean36 <- lewellen_expected_return_mean36[, Decile := ntile(Expected_Return_36, 10), by = ym]

lewellen_expected_return_mean36 <- lewellen_expected_return_mean36[!is.na(MV.USD) & !is.na(RET.USD) & Decile %in% c(1,10)]
```

### Equal Mean

```{r}
# Long the 10th decile, short the 1st decile and get the return
portfolio_returns_mean36_equal <- lewellen_expected_return_mean36 %>% 
  group_by(ym,Decile)%>%
  summarize(ret.port = mean(RET.USD)) %>% 
  spread(Decile,ret.port) %>%
  mutate(`Ret_mean36` = `10`-`1`)

# Test if the return is significantly different from 0
portfolio_returns_mean36_equal <- as.data.table(portfolio_returns_mean36_equal)
portfolio_returns_mean36_equal[,t.test(`Ret_mean36`)]
```

### Value Weighted Mean

```{r}
# Long the 10th decile, short the 1st decile and get the return
portfolio_returns_mean36_val <- lewellen_expected_return_mean36 %>% 
  group_by(ym,Decile)%>%
  summarize(ret.port = weighted.mean(RET.USD, coalesce(MV.USD, 0), na.rm = T)) %>% 
  spread(Decile,ret.port) %>%
  mutate(`Ret_mean36` = `10`-`1`)

# Test if the return is significantly different from 0
portfolio_returns_mean36_val <- as.data.table(portfolio_returns_mean36_val)
portfolio_returns_mean36_val[,t.test(`Ret_mean36`)]
```

## Returns based on Cummean

```{r}
lewellen_expected_return_cummean <- data.table(lewellen_expected_return_cummean)

setorder(lewellen_expected_return_cummean,ym,Expected_Return_cummean)

lewellen_expected_return_cummean <- lewellen_expected_return_cummean[, Decile := ntile(Expected_Return_cummean, 10), by = ym]

lewellen_expected_return_cummean <- lewellen_expected_return_cummean[!is.na(MV.USD) & !is.na(RET.USD) & Decile %in% c(1,10)]
```

### Equal Mean

```{r}
# Long the 10th decile, short the 1st decile and get the return
portfolio_returns_cummean_equal <- lewellen_expected_return_cummean %>%
  group_by(ym,Decile)%>%
  summarize(ret.port = mean(RET.USD)) %>% 
  spread(Decile,ret.port) %>%
  mutate(`Ret_cummean` = `10`-`1`)

# Test if the return is significantly different from 0
portfolio_returns_cummean_equal <- as.data.table(portfolio_returns_cummean_equal)
portfolio_returns_cummean_equal[,t.test(`Ret_cummean`)]
```

### Value Weighted Mean

```{r}
# Long the 10th decile, short the 1st decile and get the return
portfolio_returns_cummean_val <- lewellen_expected_return_cummean %>% 
  group_by(ym,Decile)%>%
  summarize(ret.port = weighted.mean(RET.USD, coalesce(MV.USD, 0), na.rm = T)) %>% 
  spread(Decile,ret.port) %>%
  mutate(`Ret_mean36` = `10`-`1`)

# Test if the return is significantly different from 0
portfolio_returns_cummean_val <- as.data.table(portfolio_returns_cummean_val)
portfolio_returns_cummean_val[,t.test(`Ret_mean36`)]
```

## regression based on expected return

```{r}
clean_mean <- lewellen_expected_return_mean36 %>% 
  select(Id,ym,RET.USD,ExRET.USD,Expected_Return_36)

clean_mean <- data.table(clean_mean)



reg_mean <- clean_mean[!is.na(Expected_Return_36) &!is.infinite(Expected_Return_36),
                       .(gamma_zero=lm(ExRET.USD~Expected_Return_36)$coefficient[1],
gamma_beta=lm(ExRET.USD~Expected_Return_36)$coefficient[2]),   
  by=ym]


reg_mean[,t.test(gamma_zero)]
reg_mean[,t.test(gamma_beta)]

```
```{r}
clean_cum <- lewellen_expected_return_cummean %>% 
  select(Id,ym,RET.USD,ExRET.USD,Expected_Return_cummean)

clean_cum <- data.table(clean_cum)



reg_cum <- clean_cum[!is.na(Expected_Return_cummean) &!is.infinite(Expected_Return_cummean),
                       .(gamma_zero=lm(ExRET.USD~Expected_Return_cummean)$coefficient[1],
gamma_beta=lm(ExRET.USD~Expected_Return_cummean)$coefficient[2]),   
  by=ym]


reg_cum[,t.test(gamma_zero)]
reg_cum[,t.test(gamma_beta)]

```
